### ISSUE TITLE
Remove Entities and plugins created

### ISSUE THREAD

**Issue by mauriziotallarico** [easyredmine/redmine_entity_generator#1]
Hello, 
could you please give me a hint on how to remove plugin/entities created by mistake ?

Thanks,
Regards
MAurizio

**Comment by mauriziotallarico** [comment]
Hello, could You please help me ?
Thanks!
regards
Maurizio

**Comment by luk4s** [comment]
Hello, you can use standard rails way. For example if you generate something by this `rails g redmine_extensions:entity easy_posts Post title:string content:text` you can revert it by `rails d redmine_extensions:entity easy_posts Post title:string content:text`.
Unfortunately revert not working properly in this version, but it will be fixed in 0.1.21 of redmine_extensions gem.
